### ISSUE TITLE
Diversification across software life cycle: Xp

### ISSUE THREAD

**Issue by maxleiko** [diverse-project/dev-dashboard#7]
Currently working on an experience with @nharrand on diversifications (with jhipster)

**Comment by maxleiko** [comment]
@nharrand update the name of the issue with the name of the paper :+1:

**Comment by templep** [comment]
What kind of experiment exactly ?
Mathieu has studied extensively JHipster Variability with Belgium guys

**Comment by maxleiko** [comment]
We are generating "clones" of a Jhipster App by just changing the version of the dependencies (kinda randomly) and only keep the ones that compile + run without issues

**Comment by nharrand** [comment]
We would like to generate clones of a jHipster app at multiple stages:
 * Design: Change jHipster configuration
 * Implementation: Change java source code of the app (with [sosiefier](https://github.com/DIVERSIFY-project/sosiefier)
* Build: Change dependencies version (in mvn pom, and bower package)
 * Shipping: Change runtime vm, vm version, and base image in docker image

**Comment by FAMILIAR-project** [comment]
somehow related https://docs.google.com/presentation/d/1574Y1wnw07aOXiuR2xGuureC5WNYfHnr_4UD1IPYOH8/edit?usp=sharing

I think I now understand what you want to do (and that's different from our "testing" work). 

I can easily imagine sosification mechanisms (impl, build, shipp) once you "fix" the JHipster configuration. 

About "change JHipster configuration" that's an interesting topic per se. 
There are two scenarios. 

At "compile time", I can imagine we can change the configuration. 
A challenge is to change the configuration (and the web stack) without actually altering the application code (if you change JHipster stack basically it will most likely remove everything). 
Beyond your sosification use case, it is a challenge to "isolate" the application code so that we can easily migrate and change the stack (JHipster configuration). 
So very interesting topic! 

Another exciting and complex scenario is to change JHipster configuration "at runtime". 
For example, change "mysql" by "mongodb". I am not aware of any technique to do that. 
What we can try is to transform "ifdef" variability as "feature toggles" for instance. 

For the two scenarios I can help

**Comment by maxleiko** [comment]
You can already play with it: https://github.com/maxleiko/diversify-mvn
